site_name: Wizeline MkDocs Template
nav:
  - Home: index.md
  - About: about.md
  - Overview: overview.md
  - Installation Guide: installation.md
  - Concepts Guide: concepts.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png